CREATE TABLE `zespoly` (
  `ID_ZESP` SMALLINT(6) PRIMARY KEY,
  `NAZWA` VARCHAR(20) NULL,
  `ADRES` VARCHAR(50) NULL
);

INSERT INTO `zespoly` (`ID_ZESP`, `NAZWA`, `ADRES`) VALUES
(10, 'ADMINISTRACJA', 'PIOTROWO 2'),
(20, 'SYSTEMY ROZPROSZONE', 'PIOTROWO 3A'),
(30, 'SYSTEMY EKSPERCKIE', 'STRZELECKA 14'),
(40, 'ALGORYTMY', 'WIENIAWSKIEGO 16'),
(50, 'BADANIA OPERACYJNE', 'MIELZYNSKIEGO 30');
